application: do-just-one-thing
version: 1
runtime: python
api_version: 1
threadsafe: true

handlers:
- url: /style
  static_dir: style

- url: /script/.*
  script: script.py

- url: /api/.*
  script: api.py

- url: /.*
  script: dojustonething.py
